services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:latest
    container_name: mealie
    ports:
      - "9925:9000"
    environment:
      ALLOW_SIGNUP: "true"
      BASE_URL: "http://localhost:9925"
    volumes:
      - mealie-data:/app/data

volumes:
  mealie-data: